name: Build Workflow

on:
  workflow_dispatch
  # workflow_run:
  #   workflows: [Check Workflow]
  #   # branches: [master]
  #   types: [completed]

jobs:
  run-deploy:
    name: Run Deploy
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Artifact From Check Workflow
        uses: actions/download-artifact@v4
        with:
          name: check-workflow-artifact-${{ github.event.pull_request.number }}
