name: Build Workflow

on:
  workflow_run:
    workflows: [Check Workflow]
    # branches: [master]
    types: [completed]

jobs:
  run-deploy:
    name: Run Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        run: echo "Hello0000"
